In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Users\\LENOVO\\OneDrive\\Desktop\\ML\\venv\\Lib\\site-packages\\numpy\\__init__.py'>

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1, 2, 3, 5 ,7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [7]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [8]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [9]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [11]:
n[0, 1] = 20

In [12]:
n[2] = [1, 1, 1]

In [13]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [14]:
n[:]

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [15]:
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [16]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [17]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]], dtype=int32)

In [18]:
a = np.arange(5)

In [19]:
a

array([0, 1, 2, 3, 4])

In [20]:
b = (10 + (a * 2)) ** 2 /100

In [21]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [22]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

In [23]:
a >= 2

array([False, False,  True,  True,  True])

In [24]:
a > b

array([False, False,  True,  True,  True])

In [25]:
a[a > b]

array([2, 3, 4])

In [26]:
 a.std()

np.float64(1.4142135623730951)

In [27]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [28]:
n.sum()

np.int64(42)

In [29]:
n[0, 2] = 0

In [30]:
n.sum()

np.int64(39)

In [31]:
# Vector multiplication

In [32]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])

In [33]:
u.shape

(4,)

In [34]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [35]:
 vector_vector_multiplication(u, v)

np.float64(110.0)

In [36]:
u.dot(v)

np.int64(110)

In [37]:
x = np.array([2, 4, 5, 6])

In [38]:
y = np.array([1, 0, 0, 2])

In [39]:
x.dot(y)

np.int64(14)

In [40]:
# Matrix-vector multiplication

In [41]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2], 
    [3, 1, 2, 1],
])

In [42]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [43]:
y

array([1, 0, 0, 2])

In [49]:
def matrix_vector_multiplication(U, y):
    assert U.shape[1] == y.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], y)

    return result

In [50]:
matrix_vector_multiplication(U, y)

array([14.,  5.,  5.])

In [54]:
U.dot(y)

array([14,  5,  5])

In [60]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
])

In [73]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros(( num_rows, num_cols ))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [81]:
matrix_matrix_multiplication(V, U)

array([[ 9. ,  8. , 10. , 10. ],
       [ 3.5,  2. ,  2.5,  2. ],
       [ 5. ,  5. ,  4. ,  5. ]])

In [79]:
V.dot(U)

array([[ 9. ,  8. , 10. , 10. ],
       [ 3.5,  2. ,  2.5,  2. ],
       [ 5. ,  5. ,  4. ,  5. ]])

In [84]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [83]:
I = np.eye(3)

In [85]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [86]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [90]:
# Identity Matrix and inverted

In [88]:
Vs_inv = np.linalg.inv(V)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [89]:
Vs_inv.dot(V)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])